name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  checkout:
    name: Checkout
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Run Trivy vulnerability scanner - FS mode
#        uses: aquasecurity/trivy-action@0.5.1
#        with:
#          scan-type: 'fs'
#          security-checks: 'vuln,config,secret'
#          hide-progress: false
#          format: 'table'
#        env:
#          AQUA_KEY: ${{ secrets.AQUA_KEY }}
#          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
#          TRIVY_RUN_AS_PLUGIN: 'aqua'
#          TRIGGERED_BY: 'PUSH'
#          GITHUB_TOKEN: ${{ github.token }}
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: "biagiodesimone/windowsvuln"
          tags: "${{ github.sha }}"
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Manifest Generation
        run: |
          docker image ls
          curl -L ${{ secrets.BILLY_URL }}/v1/api/download/sh | sh
          billy generate \
             --access-token "${{ secrets.GITHUB_TOKEN }}" \
             --aqua-key "${{ secrets.AQUA_KEY }}" \
             --aqua-secret "${{ secrets.AQUA_SECRET }}" \
             --artifact-path "biagiodesimone/windowsvuln::${{ github.sha }}"
